Repository grafana/falconlogscale-datasource, pull requests merged in 2024-02, with the labels that each got.

#230 Add a function to prepend `@timestamp` field
  pkg/plugin/query.go
  pkg/plugin/query_test.go
  pkg/test_data/prepend_timestamp_field.jsonc
Labels: effort/small

#231 Update changelog and bump version for 1.4.1
  CHANGELOG.md
  package.json
Labels: effort/none

#242 Add group to dependabot.yml for @grafana dependencies
  .github/dependabot.yml
Labels: github_actions

#245 Remove @grafana/experimental ignore from dependency group
  .github/dependabot.yml
Labels: github_actions

#95 OAuth Configuration updates
  .vscode/launch.json
  README.md
  cspell.config.json
  go.mod
  go.sum
  pkg/humio/client.go
  pkg/humio/httptransport.go
  pkg/humio/runner.go
  pkg/humio/runner_test.go
  pkg/plugin/callresource.go
  pkg/plugin/handler.go
  pkg/plugin/healthcheck.go
  pkg/plugin/plugin.go
  pkg/plugin/query.go
  pkg/plugin/query_test.go
  pkg/plugin/settings.go
  src/components/ConfigEditor.test.tsx
  src/components/ConfigEditor.tsx
  src/types.ts
Labels: effort/medium
